version: "3.9"

services:
  piglet-dev:
    image: rladmstn/piglet-dev:latest
    container_name: piglet-dev
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker

  mysql-dev:
    image: mysql:8.1
    container_name: mysql-dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: devdb
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpassword
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
