spring:
  application:
    name: lv2-final-mission
  datasource:
    url: jdbc:mysql://piglet-prod-db.:3306/piglet?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: admin
    password: 'pigletprod'
    jpa:
      hibernate:
        ddl-auto: none
      open-in-view: false
jwt:
  secret-key: bkatwhn8gqo23ywudr8miawyuercn&Q#RJOViuyjroaj983yq2uahwlejchskhskugvqiw
  validity-in-milliseconds: 30000

api:
  connection-timeout: 3000
  read-timeout: 5000

mailgun:
  api-key: fdfd1f648f95761e74866134b5ad89a8-51afd2db-6ca1b6ce
